### ISSUE TITLE
fc2HP/wikiのアカウントとパスワード

### ISSUE THREAD

**Issue by myuuuuun** [OyamaZemi/OyamaZemi.github.io#3]
@ogaway ゼミのHP/wikiで使っているfc2アカウントのアカウント名とパスワードをご存知であれば, 教えて頂けると幸いです

http://oyamaseminar.web.fc2.com/index.html
http://oyamazemi.wiki.fc2.com/

**Comment by oyamad** [comment]
@myuuuuun (内容が~~ここ~~ StudyNotes に移されているのならば) 2番目の方が残っているので消してください．

**Comment by myuuuuun** [comment]
wikiそのものがゼミのFC2アカウントで作られたものでは無いようで, 個々のページを削除することはできるのですが, wiki全体を削除することができない状態です.

**Comment by oyamad** [comment]
@ogaway 全体の消し方わかりますか．

**Comment by ghost** [comment]
どのメールアドレスで登録したかが定かではなく、心当たりあるものはどれも違ったので、問い合わせフォームから確認してみたいと思います。少し時間がかかると思います。

**Comment by ghost** [comment]
FC2から連絡が返ってきて無事ログインすることができましたので、いつでも削除できるようになりました。念のための確認ですが、こちらもう削除して差し支えございませんでしょうか。

**Comment by oyamad** [comment]
@ogaway どうもありがとう．

@myuuuuun FC2 の内容をバックアップしたら，@ogaway に削除お願いしてください．

**Comment by myuuuuun** [comment]
バックアップしました

@ogaway 削除をお願いします. お手数をおかけします

**Comment by oyamad** [comment]
@ogaway これはもう消してもらえたということでしょうか．

**Comment by ghost** [comment]
御報告し損ねており大変失礼しました。1ヶ月程度前にバックアップされた旨を確認して無事削除しております。

**Comment by oyamad** [comment]
@ogaway Thanks!
